global using Carter;
global using MediatR;
global using Mapster;
global using BuildingBlocks.Pagination;
global using Ordering.API;
global using Ordering.Application;
global using Ordering.Application.Dtos;
global using Ordering.Infrastructure;
global using Ordering.Infrastructure.Data.Extensions;